---
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-appimage:
    name: deploy AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.4
        with:
          sftp: true
          host: oxygen.monom.org
          port: 22
          username: linux-nvme
          password: ${{ secrets.SFTP_PASSWORD }}
          remote_folder: '/upload'
          local_folder: '.'
          cleanup: false
          include: '[ "*", "**/*" ]'
          exclude: '[".github/**", ".git/**", "*.env"]'
          pasive: true
